name: Dependabot updates
description: Custom GitHub action to automate the Dependabot management

inputs:
  package-ecosystem:
    description: 'Specify the list of package ecosystem names'
    required: true
  trigger-event:
    description: 'Specify the list of trigger-events'
    required: false
    default: 'push'
  interval:
    description: 'Specify the Interval on which Dependabot should be triggered'
    required: false
    default: 'daily'
    
runs:
  using: composite
  steps:
    - name: create dependabot config file
      shell: bash
      run: |
        echo "
        version: 2
        updates:
          package-ecosystem: ${{inputs.package-ecosystem}}
          directory: '/'
          schedule:
            ${{inputs.trigger-event}}"
            interval: ${{inputs.interval}}
        " > .github/dependabot.yml
    - name: trigger Dependabot
      shell: bash
      run: |
        git add .github/dependabot.yml
        git commit -m "Configured Dependabot"
        git push

version: 'v1.0.0'

branding:
  icon: 'activity'
  color: 'yellow'
