name: Dependabot updates
description: Custom GitHub action to automate the Dependabot management

inputs:
  package-ecosystem:
    description: 'Specify the list of package ecosystem names'
    required: true
  trigger-event:
    description: 'Specify the list of trigger-events'
    required: false
    default: 'push'
  interval:
    description: 'Specify the Interval on which Dependabot should be triggered'
    required: false
    default: 'daily'
    
runs:
  using: composite
  steps:
    - name: create dependabot config file and commit changes
      shell: bash
      run: |
        cd /
        echo "version: 2" > .github/dependabot.yml
        echo "updates:" >> .github/dependabot.yml
        echo "  package-ecosystem: ${{inputs.package-ecosystem}}" >> .github/dependabot.yml
        echo "  directory: '/'" >> .github/dependabot.yml
        echo "  schedule:" >> .github/dependabot.yml
        echo "    ${{inputs.trigger-event}}" >> .github/dependabot.yml
        echo "    interval: ${{inputs.interval}}" >> .github/dependabot.yml
        git add .github/dependabot.yml
        git commit -m "Configured Dependabot"
        git push

version: 'v1.0.0'

branding:
  icon: 'activity'
  color: 'yellow'
