name: Dependabot updates
description: Custom GitHub action to automate the Dependabot management
author: Aritra Banerjee

inputs:
  JIRA_EMAIL:
    description: 'Specify the JIRA email'
    required: true
  JIRA_API_TOKEN:
    description: 'Specify the JIRA API token'
    required: false
    default: 'ABC'
  PROJECT_ID:
    description: 'Specify the JIRA board ID'
    required: true
  GITHUB_TOKEN:
    description: 'Specify the GitHub token'
    required: false
    default: 'ABC'
    
runs:
  using: composite
  steps:
      - name: Create issue with Jira bot
        uses: HylandSoftware/jira-bot/create@1.2.3
        with:
          jira-base-url: https://alfresco.atlassian.net
          jira-email: ${{ inputs.JIRA_EMAIL }}
          jira-api-token: ${{ inputs.JIRA_API_TOKEN }}
          jira-project: ${{ inputs.PROJECT_ID }}
          git-email: aritra.banerjee2@hyland.com
          github-token: ${{ inputs.GITHUB_TOKEN }}

version: 'v2.0'

branding:
  icon: 'activity'
  color: 'yellow'
