name: Dependabot updates
description: Custom GitHub action to automate the Dependabot management

inputs:
  file-path:
    description: 'Specify the location of Dependabot.yml file'
    required: true
  package-ecosystem:
    description: 'Specify the list of package ecosystem names'
    required: true
  trigger-event:
    description: 'Specify the list of trigger-events'
    required: false
    default: 'push'
  interval:
    description: 'Specify the Interval on which Dependabot should be triggered'
    required: false
    default: 'daily'
    
runs:
  using: composite
  steps:
    - name: create dependabot config file and commit changes
      shell: bash
      run: |
        mkdir -p .github
        echo "version: 2" > ${{inputs.file-path}}
        echo "updates:" >> .github/dependabot.yml
        echo "  package-ecosystem: '${{inputs.package-ecosystem}}'" >> ${{inputs.file-path}}
        echo "  directory: '/'" >> ${{inputs.file-path}}
        echo "  schedule:" >> ${{inputs.file-path}}
        echo "    ${{inputs.trigger-event}}:" >> ${{inputs.file-path}}
        echo "    interval: '${{inputs.interval}}'" >> ${{inputs.file-path}}
        git add .github/dependabot.yml
        git commit -m "Configured Dependabot"
        git push

version: 'v1.0'

branding:
  icon: 'activity'
  color: 'yellow'
