name: Dependabot updates

on:
  workflow_dispatch:

jobs:
  update_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dependabot updates
        uses: ./actions/pipeline_intgration.yml
        with:
          package-ecosystem: 'npm'
